- .github/workflows/test_vscode.yml
- .github/workflows/workflow.yml
The old versions were no longer supported on GitHub Actions.
Also node: "17" was not in the list of node versions to exclude in the strategy.
Validated the changes on this nice tool:
https://rhysd.github.io/actionlint/
> chore: Fix action workflows to use the latest version

- packages/vscode-lit-plugin/src/test/simple-test.ts
Related to this error log on the `macos-latest` environment:
```shell
Extension Test Suite
✔ The extension is installed
1) We produce a diagnostic
2) We detect no-missing-import properly
✔ We generate completions (324ms)
2 passing (2m)
Error: 2 tests failed.
2 failing
at Object.<anonymous> (/Users/runner/work/lit-analyzer/lit-analyzer/packages/vscode-lit-plugin/out/test/scripts/mocha-driver.js:65:19)
1) Extension Test Suite
at Generator.next (<anonymous>)
at fulfilled (/Users/runner/work/lit-analyzer/lit-analyzer/packages/vscode-lit-plugin/out/test/scripts/mocha-driver.js:28:58)
Extension host test runner error Error: 2 tests failed.
at Object.<anonymous> (/Users/runner/work/lit-analyzer/lit-analyzer/packages/vscode-lit-plugin/out/test/scripts/mocha-driver.js:65:19)
at Generator.next …
```
> fix: Add missing awaits to test cases

- .eslintignore
- .gitignore
- .prettierignore
- lerna.json
- package-lock.json
- package.json
- packages/vscode-lit-plugin/copy-to-built.js
Quite of lot of changes on the Lerna side of things:
https://github.com/lerna/lerna/blob/main/CHANGELOG.md
Lerna also removed their `bootstrap` command, and so the monorepo had to be converted to npm workspaces (Lerna's suggestion) to achieve similar functionality:
https://lerna.js.org/docs/legacy-package-management
Had to fix a few errors that popped up as part of this migration:
- Lerna is no longer handling hoisting, so typescript had to be upgraded at the root package to match the sub-packages.
- eslint-typescript had to be upgraded to V6 in order to fix a linting error that popped up with the TS changes. This was the error that popped up: https://github.com/typescript-eslint/typescript-eslint/issues/7155#issuecomment-1692384149
- The `--parallel` flag was removed from the `lerna run` …
> chore: Upgrade Lerna to latest version

- dev/package-lock.json
- package-lock.json
- package.json
- packages/lit-analyzer/package.json
- packages/ts-lit-plugin/package.json
Neither of these are being used any longer, so removing them to clean things up a little.
> chore: Uninstall rimraf and nodemon devDependencies

- README.md
- package.json
- packages/lit-analyzer/README.md
- packages/lit-analyzer/package.json
- packages/lit-analyzer/readme/config.md
- packages/ts-lit-plugin/README.md
- packages/ts-lit-plugin/package.json
- packages/vscode-lit-plugin/README.md
- packages/vscode-lit-plugin/package.json
- packages/vscode-lit-plugin/readme/config.md
- packages/vscode-lit-plugin/readme/how.md
These commands are still configured to use [@appnest/readme](https://www.npmjs.com/package/@appnest/readme). The package was removed as a direct dependency from the monorepo since it is no longer maintained, but as long as the config files still exist then this change will keep the commands working as it did previously until an alternative to the configs can be considered.
> Fix readme commands

- .changeset/eighty-pianos-cross.md
- packages/lit-analyzer/src/lib/analyze/parse/parse-html-data/html-tag.ts
"The webcomponent analyzer returns a typehint string we can display that if it is present and there isn't any simpletype information"
https://github.com/runem/lit-analyzer/pull/357
> Return type hint information if it is available

- packages/lit-analyzer/src/lib/rules/util/type/extract-binding-types.ts
- packages/lit-analyzer/src/test/helpers/compile-files.ts
- packages/lit-analyzer/src/test/rules/no-incompatible-type-binding.ts
> This PR excludes ES symbol types from unions when checking bindings.
> This ensures that nothing and noChange are ignored in type checking.
> 
> We remove all symbol types because it is not possible to get the details of symbol types.
> This will produce false negatives when other symbols are mixed in, but I consider such situations to be rare.
> 
> Closes https://github.com/runem/lit-analyzer/issues/207. Closes https://github.com/runem/lit-analyzer/issues/251. Closes https://github.com/runem/lit-analyzer/issues/316.
> 
> This PR does not resolve the issue of ifDefined not supporting null (even though Lit v3 does).
> It will probably be resolved when we stop treating ifDefined specially, or when https://github.com/runem/lit-analyzer/pull/296 is merged.
> The user can use either a custom …
> fix: Exclude symbol when checking binding types

- .changeset/wise-grapes-applaud.md
- packages/lit-analyzer/src/lib/analyze/parse/document/text-document/html-document/parse-html-node/parse-html-node.ts
- packages/lit-analyzer/src/lib/analyze/types/html-node/html-node-types.ts
- packages/lit-analyzer/src/lib/rules/no-unclosed-tag.ts
- packages/lit-analyzer/src/test/rules/no-nullable-attribute-binding.ts
- packages/lit-analyzer/src/test/rules/no-unclosed-tag.ts
> Make this lint require explicit closing tags by checking whether parse5 has got an authored location for the endTag. Because void elements do not have an endTag we also must handle them.
https://github.com/runem/lit-analyzer/pull/340
Full details and context can be found in that PR. There are still further improvements that can be made (mentioned in that PR), but this seems like a better approach to build off of than how the rule is currently implemented.
> Simplify no-unclosed-tag rule

- .changeset/chilled-planets-hug.md
- packages/lit-analyzer/src/test/rules/no-missing-element-type-definition.ts
- packages/web-component-analyzer/src/analyze/util/ast-util.ts
- packages/web-component-analyzer/src/analyze/util/resolve-node-value.ts
- packages/web-component-analyzer/test/util/resolve-node-value.spec.ts
The idea is to make sure this change supports both static class properties, and also variables
> Tag name is correctly resolved if tag name is a static class property.
> When "discovering" custom element definitions in HTMLElementTagNameMap, where the tag name is a static class property, the node holding the property is resolved. As such lit-analyzer no-missing-element-type-definition rule behaves correctly
Not a change I made, it is taken from these two PRs:
https://github.com/runem/web-component-analyzer/pull/279
https://github.com/runem/lit-analyzer/pull/331
I added a test for the variable case, which I am hoping to also solve in this PR.
> Expand support of no-missing-element-type-definition rule

- .changeset/lemon-fans-scream.md
- packages/lit-analyzer/src/lib/rules/util/directive/get-directive.ts
- packages/lit-analyzer/src/test/rules/no-nullable-attribute-binding.ts
https://github.com/runem/lit-analyzer/pull/296
> Exclude null from the return type of ifDefined directive

- packages/lit-analyzer/src/test/indexer/index-entries.ts
https://github.com/runem/lit-analyzer/pull/294
Still seems like a good test case to have, even if there are still some things to fix around this functionality.
> Add test case for setting attribute name in @property decorator

- package.json
- packages/vscode-lit-plugin/package.json
- packages/vscode-lit-plugin/readme.config.json
- packages/vscode-lit-plugin/src/test/simple-test.ts
- readme.config.json
So that the fork can be published to VSCode, created a new VSCode Publisher and Azure Devops account.
For now the publishing is not automated, but this workflow looks like an option to potentially enable that in the future:
https://github.com/marketplace/actions/publish-vs-code-extension
> Update publisher to new name for VSCode extension

- .changeset/breezy-toes-attack.md
- .changeset/long-ducks-shave.md
Bulk description of what was changed before the initial PR that added the .changesets package to this repo.
See the individual linked PRs next to each change for details on that specific change. Going forward .changesets will be included as part of any PR that changes a user-facing feature.
I have decided to bump the major version on all packages, to help make it clear this is intended to be a continuation of existing packages and that there are breaking changes from the previous versions.
> chore: Add changeset files for major release

- package-lock.json
- package.json
- packages/lit-analyzer/src/lib/analyze/constants.ts
I had put the wrong command in the npm script, and the Changesets release PR did not update the root package-lock.json file for the internal packages.
> chore: Fix release script and update package-lock to new versions

- .changeset/quick-coins-joke.md
- packages/lit-analyzer/src/lib/rules/no-complex-attribute-binding.ts
- packages/lit-analyzer/src/lib/rules/util/type/is-assignable-in-attribute-binding.ts
- packages/lit-analyzer/src/test/helpers/generate-test-file.ts
- packages/lit-analyzer/src/test/rules/no-complex-attribute-binding.ts
- packages/lit-analyzer/src/test/rules/no-incompatible-type-binding.ts
This makes it so if the attribute on a Lit component has a [custom converter](https://lit.dev/docs/components/properties/#conversion-converter), then the plugin should not report errors related to it being passed an incompatible type. It is up to the converter to handle converting it from a string to the component type!
This change comes from the below PR from the runem repository (I just ported it over here). Thank you to the original author!
https://github.com/runem/lit-analyzer/pull/126
> fix: Consider the presence of converters when checking if attributes can be bound to the type

- .changeset/small-windows-beg.md
- packages/lit-analyzer/src/lib/analyze/parse/parse-dependencies/visit-dependencies.ts
- packages/lit-analyzer/src/test/parser/dependencies/parse-dependencies.ts
https://github.com/runem/lit-analyzer/pull/372
Not a lot of context in that PR, but I confirmed that the added test failed without this addition. It seems like a good case to handle to me.
>  Exclude imports with type-only bindings from list of dependencies to visit

- .changeset/empty-geese-study.md
- packages/lit-analyzer/src/lib/cli/compile.mts
This change was tested against this repo:
https://github.com/dfinity/internet-identity
Without this fix, it would error as is described in the comment added to the `compile.mts` file. This is a result of me converting the CLI to ESM.
Strangely, this didn't error when I installed the package locally with `npm link` or a `file:` relative path. To confirm that the error is fixed by this change, I had to push up the build output to GitHub temporarily, and install it from that using [gitpkg](https://gitpkg.vercel.app). 
For future reference, this was the install URL I used to install this specific branch for the `lit-analyzer` sub-package:
`"@jackolope/lit-analyzer": "https://gitpkg.now.sh/JackRobards/lit-analyzer/packages/lit-analyzer?fix-typescript-lit-analyzer-cli-support",`
> Fix typescript lit analyzer cli support for older versions of TypeScript (<5.5)

- .changeset/flat-months-agree.md
- dev/package-lock.json
- dev/package.json
- dev/src/my-element-1.ts
- docs/readme/rules.md
- packages/lit-analyzer/README.md
- packages/lit-analyzer/src/lib/rules/no-property-visibility-mismatch.ts
- packages/lit-analyzer/src/test/rules/no-property-visibility-mismatch.ts
- packages/ts-lit-plugin/README.md
- packages/vscode-lit-plugin/README.md
The `@internalProperty` decorator was deprecated and renamed to `@state`. It seems like this rule was just not updated to reflect this when that change was made to Lit.
Fixes #132
> feat: Update `no-property-visibility-mismatch` rule to check for @state instead of @internalProperty

- .changeset/eager-lies-judge.md
- .changeset/fast-ways-prove.md
- .changeset/vast-jars-sleep.md
- .changeset/violet-hats-decide.md
- docs/readme/rules.md
- packages/lit-analyzer/README.md
- packages/lit-analyzer/src/lib/analyze/lit-analyzer-config.ts
- packages/lit-analyzer/src/lib/rules/no-incompatible-property-type.ts
- packages/lit-analyzer/src/lib/rules/util/type/is-assignable-in-property-binding.ts
- packages/lit-analyzer/src/test/rules/no-incompatible-property-type.ts
- packages/lit-analyzer/src/test/rules/no-incompatible-type-binding.ts
- packages/lit-analyzer/src/test/rules/no-nullable-attribute-binding.ts
- packages/ts-lit-plugin/README.md
- packages/ts-lit-plugin/readme/config.md
- packages/ts-lit-plugin/src/index.ts
- packages/vscode-lit-plugin/README.md
Changes:
- `no-nullable-attribute-binding` rule is now `off` by default on both the default and strict rulesets. Newer versions of Lit handle removing `null` or `undefined` in attribute bindings for you, so you do not need this rule unless you still are using an old Lit version. See this issue: https://github.com/runem/lit-analyzer/issues/253
- `no-incompatible-property-type` rule will now not report an error if `state:true` is configured using the `@property` decorator. This matches how the rule behaves for `attribute: false`, since they both indicate that this is not an attribute and so does not need a type converter.
- `no-incompatible-type-binding` now ignores `undefined` in union types when binding with a property (`.`). This is because there is no way to mark a property as …
> Fix a few minor things around the plugin

- .changeset/cold-toys-leave.md
- packages/lit-analyzer/src/lib/analyze/data/get-built-in-html-collection.ts
- packages/lit-analyzer/src/lib/analyze/data/get-user-config-html-collection.ts
- packages/lit-analyzer/src/lib/analyze/default-lit-analyzer-context.ts
- packages/lit-analyzer/src/lib/analyze/parse/parse-html-data/parse-vscode-html-data.ts
- packages/vscode-lit-plugin/src/extension.ts
The extension should now react to the VSCode `html.customData` setting:
https://github.com/microsoft/vscode-html-languageservice/blob/main/docs/customData.md
Most of the code to handle this already existed, it was just still looking at `html.experimental.customData` and hadn't been updated.
I've tested it using these two basic samples:
- https://github.com/microsoft/vscode-custom-data/blob/main/samples/webcomponents/src/web-components.html-data.json
- https://github.com/octref/vscode-mavo/blob/master/data/mavo.json
If you run into any issues or missing features from a more complex customData setup let me know! It's possible that the `customData` spec was updated since this original logic was added, but I couldn't find anything that indicated that.
Also improved error handling and logging …
> feat: Add support for `html.customData` setting

- .changeset/real-bags-press.md
- packages/lit-analyzer/src/lib/rules/util/type/is-assignable-in-property-binding.ts
- packages/lit-analyzer/src/test/rules/no-incompatible-type-binding.ts
Reverting one of the changes from this PR:
https://github.com/JackRobards/lit-analyzer/pull/207
Considering reverting this change...
Two reasons for reverting this:
- Thinking more about it: how it was working before makes more sense - if undefined is possible, then the types should reflect that.
- If we are doing to do something like this, then I think we should look for a slightly more performant solution. The rule checks can run a lot of times to validate the templates, so we need to be careful when adding logic like this to a rule.
There is some performance logging in the tools, but it would be nice if there were some automated tests to track this. It's a little hard to tell what the performance impact of a change is as-is 🤔.
> Revert no incompatible type undefined union

- .changeset/dependabot-d280ae6-@jackolope-lit-analyzer.md
- .changeset/dependabot-d280ae6-@jackolope-ts-lit-plugin.md
- .changeset/dependabot-d280ae6-@jackolope-web-component-analyzer.md
- .changeset/dependabot-d280ae6-lit-analyzer-plugin.md
- scripts/create-dependency-changesets.mjs
Adds a script for creating dependabot changesets, and adds the changesets for the updates since the last release.
Could be further improved from here, but this seems like a good starting point to me.
> Create dependabot changesets script

- .changeset/funny-doodles-worry.md
- .changeset/zzz_dependabot-76e43ac-@jackolope-lit-analyzer.md
- .changeset/zzz_dependabot-76e43ac-@jackolope-ts-lit-plugin.md
- .changeset/zzz_dependabot-76e43ac-lit-analyzer-plugin.md
- package-lock.json
- packages/vscode-lit-plugin/README.md
- packages/vscode-lit-plugin/package.json
- packages/vscode-lit-plugin/schemas/tsconfig.schema.json
- packages/vscode-lit-plugin/src/color-provider.ts
- packages/vscode-lit-plugin/src/extension.ts
- packages/vscode-lit-plugin/src/folding-provider.ts
- packages/vscode-lit-plugin/src/utils.ts
- scripts/create-dependency-changesets.mjs
This leverages the `vscode-html-languageservice` and `vscode-css-languageservice` packages to provide a [VSCode FoldingRangerProvider](https://code.visualstudio.com/api/references/vscode-api#FoldingRangeProvider) for these tagged template literals that Lit uses. Since it is re-using the folding logic from these extensions directly, it keeps the logic here pretty simple and works well enough from my testing to be very useful!
There is a new `lit-analyzer-plugin.enableTaggedTemplateFolding` vscode setting to enable/disable this feature. By default it is enabled, unless you have the `editor.foldingStrategy` set to "indendation" in vscode. 
I have noticed a little weirdness when multiple `html` template literals are nested inside each other. The change in this PR doesn't break anything in …
> Add folding (code collapse) support to html, css, and svg template literals

- .changeset/curvy-badgers-count.md
- packages/web-component-analyzer/src/analyze/flavors/custom-element/discover-members.ts
- packages/web-component-analyzer/src/analyze/util/ast-util.ts
- packages/web-component-analyzer/test/flavors/custom-element/visibility-test.ts
The same idea as [this change](https://github.com/JackRobards/lit-analyzer/pull/258/files), but handling it in the `web-component-analyzer` package.
There was related logic in the `ast-util.ts` file for the handling the visibility in the `getMemberVisibilityFromNode` method. It wasn't working correctly for `#` private properties, and fixing that should fix the problem with the `no-property-visibility-mismatch` rule.
This should also make these properties get detected correctly anywhere else the `visibility` matters in the rules. As far as I know it only effects this one rule currently though
> fix(web-component-analyzer): Add support for identifying the visibility of JavaScript private (#) properties

- .changeset/shaky-ghosts-watch.md
- packages/lit-analyzer/src/lib/rules/no-noncallable-event-binding.ts
- packages/lit-analyzer/src/test/rules/no-noncallable-event-binding.ts
The essence of `@eventOptions()` is to do [Object.assign(method, options)](https://github.com/lit/lit/blob/main/packages/reactive-element/src/decorators/event-options.ts)
In some cases, instead of using `@eventOptions()`, event-options can be configured directly through `Object.assign`.
Therefore, it is necessary to add support for the INTERSECTION type check.
> 🐛 fix `no-noncallable-event-binding` work with 'INTERSECTION' kind

- .github/dependabot.yml
- .github/workflows/dependabot-automerge.yml
Two new ones added:
- Automate increasing `github-actions` versions: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
- Ability to auto-merge certain devDependencies for minor and patch versions (`eslint` and `@types` ones for now)
> Chore: Add more Github Actions dependabot workflows

- README.md
- packages/lit-analyzer/README.md
- packages/ts-lit-plugin/README.md
- packages/vscode-lit-plugin/README.md
- packages/vscode-lit-plugin/readme/header.md
- packages/web-component-analyzer/README.md
david-dm badge urls do not work consistently, so switching these over to libraries,io when I have some time to look into it.
> chore: Update david-dm badge links to new URL

- .github/workflows/dependabot-automerge.yml
- package-lock.json
- packages/vscode-lit-plugin/package.json
The auto-merge check bumped the `@types/vscode` version to one higher than the specified `engines.vscode` version, which has started causing the build to fail.
The extension hasn't started to use the newer vscode features yet, so we don't need to update the `engines.vscode` version.
> chore: Downgrade @types/vscode version to match the engines.vscode version specified in the extension package.json

- .changeset/social-months-divide.md
- CONTRIBUTING.md
- packages/vscode-lit-plugin/package.json
- packages/vscode-lit-plugin/syntaxes/vscode-lit-html/lit-html.json
- packages/vscode-lit-plugin/syntaxes/vscode-lit-html/text.html.lit-template.json
The aim here is to slightly improve the syntaxes by adding a custom `text.html` for Lit's tagged template literals. The previous version used `"text.html.basic"` which works very well in most cases, but I noticed that it would sometimes have issues in the occasional Lit template.
I used the syntaxes from [vsc-ember-syntax](https://github.com/lifeart/vsc-ember-syntax/tree/master/syntaxes) for reference with these. They were a big help in figuring out how to structure this - so thank you to the original author(s)! The versions here are based on those, but greatly simplified (Lit does not use handlebars or other Glimmer features) and adjusted a bit to support Lit templates.
I don't think most users will notice any major difference from this change. In the majority of cases the `html` …
> feat(syntaxes): Lit html syntax updates

- .changeset/deep-ways-heal.md
- package-lock.json
tar-fs vulnerability:
https://security.snyk.io/vuln/SNYK-JS-TARFS-9535930
undici vulnerability:
https://security.snyk.io/vuln/SNYK-JS-UNDICI-8641354
These dependencies are only used as part of the VSCode extension and are installed via the `@vscode/vsce` package.
> chore: Ran `npm audit fix` to address vulnerabilities

- .changeset/wide-cooks-mate.md
- .changeset/zzz_dependabot-9af072e-@jackolope-lit-analyzer.md
- .changeset/zzz_dependabot-9af072e-@jackolope-ts-lit-plugin.md
- .changeset/zzz_dependabot-9af072e-@jackolope-web-component-analyzer.md
- .changeset/zzz_dependabot-9af072e-lit-analyzer-plugin.md
- package-lock.json
Changeset files to trigger the new release.
The only user-facing changes since the last release have been the `vscode` related dependencies, but it would be nice to do a small release to keep these up-to-date.
Also fixing two small `npm audit` issues in this PR.
> chore: Generate dependency update changesets

- .changeset/slow-parents-sin.md
- packages/lit-analyzer/src/lib/rules/no-missing-import.ts
- packages/lit-analyzer/src/test/rules/no-missing-import.ts
Fixes this issue by skipping this rule for any tags that were listed in the `globalTags` config.
fixes: #299 
Also added a test separate test for the type-only import case that was fixed awhile ago in this PR:
https://github.com/JackRobards/lit-analyzer/pull/111
> fix: Update no-missing-import rule to avoid reporting on any listed globalTags

- .changeset/khaki-rats-drive.md
- packages/ts-lit-plugin/index.js
The ts-lit-plugin entry does not seem to point at the correct module.
```
$ ls node_modules/@jackolope/ts-lit-plugin/lib/index*
zsh: no matches found: node_modules/@jackolope/ts-lit-plugin/lib/index*
$ ls node_modules/@jackolope/ts-lit-plugin/lib/src/index*
node_modules/@jackolope/ts-lit-plugin/lib/src/index.d.ts
node_modules/@jackolope/ts-lit-plugin/lib/src/index.d.ts.map
node_modules/@jackolope/ts-lit-plugin/lib/src/index.js
node_modules/@jackolope/ts-lit-plugin/lib/src/index.js.map
```
After the fix, the plugin gets properly loaded and I get intellisense in neovim again.
> fix: ts-lit-plugin entry

- .changeset/yellow-boxes-hang.md
- packages/vscode-lit-plugin/copy-to-built.js
Basically, allow the `ts-lit-plugin` to control it's own `index.js` entry file how it needs to without worrying about the vscode extension reaching across packages to copy the file directly.
Directly related to this PR:
https://github.com/JackRobards/lit-analyzer/pull/384
Some parts of the `copy-to-built.js` file still feels a little "hacky" to me, but this keeps it working while letting us fix the issue from the above PR in `ts-lit-plugin`.
> fix: Remove cross package dependency from the vscode lit plugin build 
